main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
	path("", views.homepage, name="homepage"),
	path("register", views.register, name="register"),
	path("logout", views.logout_request, name="logout"),
    path("login", views.login_request, name="login"),
    path("addalbum", views.add_album, name="addalbum"),
    path("updatealbum/<single_slug>", views.update_album, name="updatealbum"),
    path("account", views.account, name="account"),
    path("ratealbum", views.RateAlbumView.as_view(), name="ratealbum"),
    path("<single_slug>", views.single_slug, name="single_slug"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator

# Create your models here.

class Genre(models.Model):
	genre = models.CharField(max_length=200)
	genre_description = models.TextField(default="No Description")
	genre_image_url = models.CharField(max_length=200, default="https://img.discogs.com/G0haDbUa-_stv3xTv9R5ip4fAKo=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-238369-1490362449-5582.jpeg.jpg")

	genre_slug = models.CharField(max_length=200, default=1)

	class Meta:
		verbose_name_plural = "Genres"

	def __str__(self):
		return self.genre

class Artist(models.Model):
	artist_name = models.CharField(max_length=200)
	artist_age = models.IntegerField()
	label_name = models.CharField(max_length=200)
	artist_description = models.TextField(default="No Description")
	artist_image_url = models.CharField(max_length=200, default="https://images.genius.com/6d0fbbc7ce189a8c81671ef92546446e.1000x1000x1.png")

	artist_slug = models.CharField(max_length=200, default=1)

	class Meta:
		verbose_name_plural = "Artists"

	def __str__(self):
		return self.artist_name


class Album(models.Model):
	album_name = models.CharField(max_length=200)
	artist_name = models.ForeignKey(Artist, default=1, verbose_name="Artist", on_delete=models.SET_DEFAULT)
	album_cover_url = models.CharField(max_length=200, default="https://assets.genius.com/images/default_cover_image.png?1596138983")

	# artist_name = models.CharField(max_length=200)
	release_date = models.DateField("release date")
	album_description = models.TextField()
	is_single = models.BooleanField(default=False)
	genre = models.ForeignKey(Genre, default=1, verbose_name="Genre", on_delete=models.SET_DEFAULT)

	album_slug = models.CharField(max_length=200, default=1)

	author = models.ForeignKey(User, default=1, on_delete=models.SET_DEFAULT)

	class Meta:
		verbose_name_plural = "Albums"
		unique_together = ["artist_name", "album_name"]

	def __str__(self):
		return self.album_name

class Track(models.Model):
	track_name = models.CharField(max_length=200)
	album_name = models.ForeignKey(Album, default=1, verbose_name="Album", on_delete=models.SET_DEFAULT)
	artist_name = models.ForeignKey(Artist, default=1, verbose_name="Artist", on_delete=models.SET_DEFAULT)
	track_number = models.IntegerField(default=1)
	track_lyrics = models.TextField(default="")
	
	track_slug = models.CharField(max_length=200, default=1)

	class Meta:
		verbose_name_plural = "Tracks"
		unique_together = ["artist_name", "track_name"]

	def __str__(self):
		return "{} by {}".format(self.track_name, self.artist_name)

class AlbumRating(models.Model):
	username = models.ForeignKey(User, default=1, verbose_name="User", on_delete=models.CASCADE)
	album_name = models.ForeignKey(Album, default=1, verbose_name="Album", on_delete=models.CASCADE)
	rating = models.IntegerField(validators=[MaxValueValidator(10)])
	review = models.TextField(default="")

	class Meta:
		verbose_name_plural = "Album Ratings"

	def __str__(self):
		return "{} - {} - {}".format(self.album_name, self.username, self.rating)

class TrackRating(models.Model):
	username = models.ForeignKey(User, default=1, verbose_name="User", on_delete=models.CASCADE)
	track_name = models.ForeignKey(Track, default=1, verbose_name="Track", on_delete=models.CASCADE)
	rating = models.IntegerField(validators=[MaxValueValidator(10)])
	review = models.TextField(default="")

	class Meta:
		verbose_name_plural = "Track Ratings"

	def __str__(self):
		return "{} - {} - {}".format(self.album_name, self.username, self.rating)

main/forms.py
from django import forms
from .models import Album, Genre, Artist, AlbumRating, TrackRating
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from bootstrap_modal_forms.forms import BSModalModelForm

class RateAlbumForm(BSModalModelForm):
	class Meta:
		model = AlbumRating
		fields = ['album_name', 'rating', 'review']

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

class NewAlbumForm(forms.ModelForm):
	album_name = forms.CharField(label='Album Name', max_length=200)
	temp_artist = forms.CharField(label='Artist Name', max_length=200)
	release_date = forms.DateField(label="Release Date", initial='YYYY-MM-DD')

	# album_description = forms.TextField()
	# is_single = forms.BooleanField()

	temp_genre = forms.CharField(label='Genre', max_length=200)

	album_slug = forms.CharField(label='Album Slug', initial='album-name-artistname', max_length=200)

	class Meta:
		model = Album
		fields = ['album_name', 'temp_artist', 'release_date', 'temp_genre', 'album_slug']

	def save(self, commit=True):
		album = super(NewAlbumForm, self).save(commit=False)
		album.album_name = self.cleaned_data['album_name']

		artists = [a.artist_name for a in Artist.objects.all()]
		artist_name = self.cleaned_data['temp_artist']
		if artist_name in artists:
			album.artist_name = Artist.objects.get(artist_name=artist_name)
		else:
			album.artist_name = Artist(artist_name=self.cleaned_data['temp_artist'], artist_age=0, label_name="", artist_slug="-1")
			album.artist_name.save()

		genres = [g.genre for g in Genre.objects.all()]
		genre = self.cleaned_data['temp_genre']
		if genre in genres:
			album.genre = Genre.objects.get(genre=genre)
		else:
			album.genre = Genre.objects.get(genre="Other")

		album.release_date = self.cleaned_data['release_date']
		# album.album_description = self.cleaned_data['album_description']
		# album.is_single = self.cleaned_data['is_single']
		album.album_slug = self.cleaned_data['album_slug']

		if commit:
			album.save()
		return album

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Album, Artist, Track, Genre, AlbumRating, TrackRating
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from .forms import NewUserForm, NewAlbumForm, RateAlbumForm
from django.db.models import Avg
from main.scripts.scrape import Scrape

from django.urls import reverse_lazy
from bootstrap_modal_forms.generic import BSModalCreateView

# Create your views here.
def single_slug(request, single_slug):

	# Handling for Genre page
	# If slug is a genre slug, redirect to genre.html with a dictionary matching albums to their slugs
	genres = [g.genre_slug for g in Genre.objects.all()] #All genre slugs
	if single_slug in genres:
		matching_albums = Album.objects.filter(genre__genre_slug=single_slug) #Get Album with corresponding genre

		album_urls = {}
		for m in matching_albums.all():
			# part_one = Track.objects.filter(album_name__album_name=m.album_name).earliest("track_number")
			# album_urls[m] = part_one.track_slug
			album_urls[m] = m.album_slug

		return render(request,
			"main/genre.html",
			{"albums":album_urls})


	# Handling for album page
	# If slug is an album slug, redirect to album.html with the album object, artist object, and all album ratings for that album.
	albums = [a.album_slug for a in Album.objects.all()]
	if single_slug in albums:
		this_album = Album.objects.get(album_slug=single_slug)
		this_artist = Artist.objects.get(artist_name=this_album.artist_name)
		album_ratings = AlbumRating.objects.filter(album_name__album_name=this_album.album_name)
		average_rating = album_ratings.aggregate(Avg('rating'))
		album_tracks = Track.objects.filter(album_name__album_name=this_album.album_name)

		return render(request,
			"main/album.html",
			{"album":this_album, "artist":this_artist, "ratings":album_ratings, "score":average_rating['rating__avg'], "tracks":album_tracks})

	# Handling for track page
	# If slug is an track slug, redirect to track.html 
	tracks = [t.track_slug for t in Track.objects.all()]
	if single_slug in tracks:
		this_track = Track.objects.get(track_slug=single_slug)
		this_album = Album.objects.get(album_name=this_track.album_name)
		this_artist = Artist.objects.get(artist_name=this_track.artist_name)
		track_ratings = TrackRating.objects.filter(track_name__track_name=this_track.track_name)
		average_rating = track_ratings.aggregate(Avg('rating'))

		album_tracks = Track.objects.filter(album_name__album_name=this_album.album_name)

		return render(request,
			"main/track.html",
			{"track": this_track, "album":this_album, "artist":this_artist, "ratings":track_ratings, "score":average_rating['rating__avg'], "tracks":album_tracks})

	return HttpResponse("{} does not correspond to anything.".format(single_slug))

# Homepage, shows all genres : Later shows different pages to redirect to
def homepage(request):
	return render(request=request,
		template_name="main/genres.html",
		context={"genres": Genre.objects.all})

# Register view, initially renders register.html, where the user can fill out a form that redirects back here with the request.method = POST
# Once user is created, logs user in and redirects to homepage
def register(request):
	if request.method == "POST":
		form = NewUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			username = form.cleaned_data.get("username")
			messages.success(request, "New Account Created: {}".format(username))
			login(request, user)
			return redirect("main:homepage")
		else:
			for msg in form.error_messages:
				messages.error(request, "{}: {}".format(msg, form.error_messages[msg]))

	form = NewUserForm
	return render(request,
		"main/register.html",
		context={"form": form})

# Logout and redirect to homepage
def logout_request(request):
	logout(request)
	messages.info(request, "Logged out.")
	return redirect("main:homepage")

# Login view initially renders login.html where user fills out login form and redirects here with method == POST
# Authenticate user and then log them in and redirect to homepage
def login_request(request):
	if request.method == "POST":
		form = AuthenticationForm(request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)

			if user is not None:
				login(request, user)
				messages.success(request, "Logged in as: {}".format(username))
				return redirect("main:homepage")
			else:
				messages.error(request, "Invalid username or password.")
		else:
			messages.error(request, "Invalid input.")

	form = AuthenticationForm()
	return render(request,
		"main/login.html",
		{"form":form})

# Add album initially renders addalbum.html where user can fill out NewAlbumForm.
# Redirects back to genre where Album was added
# Currently runs into error when adding album with an unregistered artist, although it creates the artist - Go back and retry and it should work - NEEDS FIX
def add_album(request):
	if request.method == "POST":
		form = NewAlbumForm(request.POST)
		if form.is_valid():
			album = form.save()
			album_name = form.cleaned_data.get('album_name')
			genre = form.cleaned_data.get('temp_genre')

			genre_slug = Genre.objects.get(genre=genre).genre_slug
			print(genre_slug)

			messages.success(request, "New Album Posted")

			return redirect('main:single_slug', genre_slug)
		else:
			messages.error(request, "Invalid input.")

	form = NewAlbumForm
	return render(request,
		"main/addalbum.html",
		context={"form": form})
			# album_name = form.cleaned_data.get('album_name')
			# artist_name = form.cleaned_data.get('artist_name')
			# release_date = form.cleaned_data.get('release_date')
			# album_description = form.cleaned_data.get('album_description')
			# is_single = form.cleaned_data.get('is_single')
			# genre = form.cleaned_data.get('genre')
			# album_slug = form.cleaned_data.get('album_slug')

# Once album is created, it is an empty page with nothing but the information provided in the form
# Takes in slug of the album it wants to update
# Scrapes tracklist based off artist name and album name
# For each track in the tracklist, scrapes lyrics
# Gets album cover using 3rd track in the list and artist name - NEEDS TO BE UPDATED TO USE ALBUM NAME
# Very buggy and unreliable
def update_album(request, single_slug):
	albums = [a.album_slug for a in Album.objects.all()]
	if single_slug in albums:
		this_album = Album.objects.get(album_slug=single_slug) 
		this_artist = Artist.objects.get(artist_name=this_album.artist_name) 

		album_name = this_album.album_name
		artist_name = this_artist.artist_name

		# Scraping the lyrics does not always work, I still don't understand why, sometimes the page takes too long to load so the request doesn't pull the data
		# This constant is the number of times it should try to scrape lyrics for each track
		LOOP_COUNT = 5
		count = 0

		# Get Track List
		track_list = Scrape.getTrackList(this_artist.artist_name, this_album.album_name)

		# Enumerate to get Track Numbers in order
		for i, ele in enumerate(track_list, start=1):
			# Create Slug
			track_slug = Scrape.createSlug(artist_name, ele)

			# Temporary fix, uses the third song to find the cover for the album, makes sure that a file is not already stored
			if i == 2 and this_album.album_cover_url[-3:] not in ['png', 'jpg', 'bmp']:
				this_album.album_cover_url = Scrape.getAlbumCoverURL(artist_name, ele)

			# CHECK if artist already has track with the same name
			artist_tracks = Track.objects.filter(artist_name__artist_name=artist_name)
			track_names = [t.track_name for t in artist_tracks]
			this_track = ""

			# If this track exists in the list of this artist's tracks, get the track and update it's fields
			if ele in track_names:
				this_track = Track.objects.get(track_name=ele, artist_name=this_artist)
				this_track.album_name = this_album
				this_track.track_number = i
				if this_track.track_lyrics == "404" or this_track.track_lyrics == "":
					track_lyrics = Scrape.getSongLyrics(artist_name, ele)

					# Loop until lyrics are retrieved or counter runs out
					while(track_lyrics == "404" and count < LOOP_COUNT):
						track_lyrics = Scrape.getSongLyrics(artist_name, ele)
						count+=1

				this_track.track_slug = track_slug
				this_track.save() # Save changes to model
			else:	# If it doesn't exist
				track_lyrics = Scrape.getSongLyrics(artist_name, ele)
				while(track_lyrics == "404" and count < LOOP_COUNT):
					track_lyrics = Scrape.getSongLyrics(artist_name, ele)
					count+=1
				this_track = Track(track_name=ele, album_name=this_album, artist_name=this_artist, track_number=i, track_lyrics=track_lyrics, track_slug=track_slug)
				this_track.save()
			count = 0

		# print(track_list)
		this_album.save() # Save changes to model
		this_artist.artist_slug = Scrape.createSlug(artist_name, "")

		this_artist.save()
		return redirect('main:single_slug', single_slug)

# Account view renders user information and previous ratings
def account(request):
	user = request.user

	album_ratings = AlbumRating.objects.filter(username__username=user.username)
	track_ratings = TrackRating.objects.filter(username__username=user.username)
	albums = Album.objects.all()
	tracks = Track.objects.all()

	return render(request=request,
		template_name="main/account.html",
		context={"albums_ratings" : album_ratings, "track_ratings" : track_ratings, "albums" : albums, "tracks" : tracks})

def rate_album(request):
	form = RateAlbumForm(request.POST)
	return render(request,
		"main/ratealbum.html",
		context={"form": form})


main/templates/main/account.html
{% extends "main/header.html" %}

{% block content %}

{% if user.is_authenticated %}

    <div class="row">

        <div class="col s12, m8, l8">
            <h3>{{user.username}}</h3>
        </div>

    </div>

    <div class="row">

    <h5>Albums Rated</h5>
     <ul class="collection">
      {% for a in albums %}
          <li class="collection-item"><b>{{a.album_name}}</b></li>
           {% for t in tracks %}
           <!-- t.album_name references an album object, must be returned in stringformat -->
            {% ifequal t.album_name|stringformat:"s" a.album_name %}
              <li>{{t.track_name}}</li>
            {% endifequal %}
       
          {% endfor %}
      {% endfor %}

      </ul>
      <div class="col s3">
         
      </div>

      <div class="col s9">
          
      </div>

    </div>
{% endif %}
{% endblock %}

main/templates/main/addalbum.html
{% extends "main/header.html" %}

{% block content %}
<div class="container">
{% if user.is_authenticated %}
  <form method="POST">
    {% csrf_token %}
    {{form.as_p}}

    <br>
    <button class="btn" type="submit">Add Album</button>
  </form>
{% endif %}
</div>
{% endblock %}

main/templates/main/album.html
{% extends "main/header.html" %}

{% block extra_js %}
<script type="text/javascript">
$(document).ready(function() {

    $("#ratealbum").modalForm({
        formURL: "{% url 'main:ratealbum' %}"
    });

});
</script>
<script src="http://malsup.github.com/jquery.form.js"></script>
{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
      <br>
      <img src={{album.album_cover_url}} style="float:left" width="200" height="200">
        <div class="col s12, m8, l8">
            <h3>{{album.album_name}}</h3>
            <h5><b><a href="{{artist.artist_slug}}">{{artist.artist_name}}</a></b></h5>
            <p style="font-size:80%">Published {{album.release_date}}</p>
        </div>

{% if user.is_authenticated %}
<br>
<br>
<a href="ratealbum" class="waves-effect waves-light btn"><i class="material-icons right">star_border</i>Rate</a>
<button id="ratealbum" class="btn btn-primary" type="button" name="button">Create book</button>

<div class="modal fade" tabindex="-1" role="dialog" id="modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      

    </div>
  </div>
</div>

{% endif %}
    </div>

    <div class="row">

      <div class="col s3">
        <h6>Rating: {{score}}</h6>

          <ul class="collection">
          	{% for ele in tracks %}
		    <a href="{{ele.track_slug}}"><li class="collection-item avatar">
		      <img src="{{album.album_cover_url}}" alt="" class="circle">
		      <span ="title">{{ele.track_name|safe}}</span>
		      <p><br>
		      </p>
		      <a class="secondary-content"><i class="material-icons"></i>{{ele.track_number|safe}}</a>
		    </li> </a>
		    {% endfor %}
		  </ul>

      </div>

      <div class="col s9">
           <p>{{album.album_description|safe}}</p>
      </div>

    </div>

</div>
{% if user.is_authenticated %}
  <a href="updatealbum/{{album.album_slug}}" class="float">
    <i class="fa fa-plus my-float" style="font-size:250%">#</i>
  </a>
{% endif %}


{% endblock %}

main/templates/main/genre.html
{% extends "main/header.html" %}

{% block content %}
<div class="container">
    <br>
    <div class="row">
        {% for album, slug in albums.items %}

            <div class="col s12 m6 l4">
                <a href="{{slug}}", style="color:#000">
                    <div class="card hoverable">
                        <div class="card-content">
                            <div class="card-title">{{album.album_name}}</div>
                            <img class="activator" src="{{album.album_cover_url}}" style="width:285px;height:285px">
                            <p>{{album.artist_name}}</p>
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
    

    </div>
</div>
{% if user.is_authenticated %}
  <a href="addalbum" class="float">
    <i class="fa fa-plus my-float" style="font-size:240%">+</i>
  </a>
{% endif %}
{% endblock %}

main/templates/main/genres.html
{% extends "main/header.html" %}

{% block content %}
  <div class="container">
    <br>
  <div class="row">
      {% for ele in genres %}
          <div class="col s12 m6 l4">
              <a href="{{ele.genre_slug}}", style="color:#000">
                  <div class="card small    hoverable">
                      <div class="card-content">
                          <div class="card-title">{{ele.genre}}</div>
                          <!--<p style="font-size:70%">Published {{tut.tutorial_published}}</p>-->
                          <p>{{ele.genre_description}}</p>
                      </div>
                  </div>
              </a>
          </div>
      {% endfor %}
  </div>
</div>
{% endblock %}

main/templates/main/header.html
<head>
{% load static %}
<link href="{% static 'tiny/css/prism.css' %}" rel="stylesheet">
<!-- Compiled and minified CSS -->
<link href="{% static 'main/css/materialize.css' %}" rel="stylesheet">
 <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link rel="stylesheet" href="{% static 'assets/css/bootstrap.css' %}">

<!-- Compiled and minified JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

<style>

.float{
	position:fixed;
	width:60px;
	height:60px;
	bottom:40px;
	right:40px;
	background-color:#0C9;
	color:#FFF;
	border-radius:50px;
	text-align:center;
	box-shadow: 2px 2px 3px #999;
}

.my-float{
	margin-top:22px;
}

</style>
</head>

<body>

 {% include "main/includes/navbar.html" %}

 {% include "main/includes/messages.html" %}

<script src="{% static 'assets/js/bootstrap.js' %}"></script>
<script src="{% static 'assets/js/jquery.js' %}"></script>
<script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>


    {% block content %}
    {% endblock %}


</body>

<footer class="page-footer">
  <div class="container">
    <div class="row">
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2020 Michael Sheroubi
    <a class="grey-text text-lighten-4 right" href="https://msheroubi.github.io">More about me</a>
    </div>
  </div>
</footer>


<script src="{% static 'tinymce/js/prism.js' %}"></script>

main/templates/main/home.html
{% extends "main/header.html" %}

{% block content %}

  <div class="row">
  	{% for ele in albums %}
    <div class="col s12 m6 l4">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"> {{ele.album_name}}</span>
	          <p style="font-size:70%"> {{ele.release_date}} </p>
	          <p> <b> {{ele.artist_name}} </b> </p>
	          <p> {{ele.album_description}} </p>
        </div>
        <div class="card-action">
          <a href="#">Visit</a>
        </div>
      </div>
      {% endfor %}
    </div>

{% endblock %}

main/templates/main/login.html
{% extends "main/header.html" %}

{% block content %}

  <form method="POST">
    {% csrf_token %}
    {{form.as_p}}

    <br>
    <button class="btn" type="submit">Login</button>
  </form>

  If you don't have an account, <a href="/register"><b>Register</b></a>.

{% endblock %}

main/templates/main/ratealbum.html
<form class="well contact-form" method="post" action="/contact/edit/{{ item.id }}">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">×</button>
    <h3>Editing Contact</h3>
  </div>
  <div class="modal-body">
       {% csrf_token %}
       {{form.as_p}}
  </div>
  <div class="modal-footer">
       <input class="btn btn-primary" type="submit" value="Save" />
       <input name="cancel" class="btn" type="submit" value="Cancel"/>
  </div>
</form>

main/templates/main/register.html
{% extends "main/header.html" %}

{% block content %}
<div class="container">
  <form method="POST">
    {% csrf_token %}
    {{form.as_p}}

    <br>
    <button class="btn" type="submit">Register</button>
  </form>

  If you already have an account, <a href="/login"><b>login</b></a> instead.
</div>
{% endblock %}

main/templates/main/track.html
{% extends "main/header.html" %}

{% block content %}

<div class="container">
<br> 
<a href="{{album.album_slug}}"><img src={{album.album_cover_url}} style="float:left" width="200" height="200"></a>
    <div class="row">

        <div class="col s12, m8, l8">
            <a href="{{album.album_slug}}" style="font-size:100%"><b>{{album.album_name}}</b></a>
            <h4>{{track.track_name|safe}}</h4>
            <h5><b><a href="{{artist.artist_slug}}">{{artist.artist_name}}</a></b></h5>
            <p style="font-size:80%">Published {{album.release_date}}</p>
        </div>
{% if user.is_authenticated %}
<br><br>
<a href="ratealbum/{{album.album_slug}}" class="waves-effect waves-light btn"><i class="material-icons right">star_border</i>Rate</a>
{% endif %}
    </div>

    <div class="row">

      <div class="col s3">
        <h6>Rating: {{score}}</h6>

          <ul class="collection">
            {% for ele in tracks %}
            <a href="{{ele.track_slug}}"><li class="collection-item avatar">
              <img src="{{album.album_cover_url}}" alt="" class="circle">
              <span ="title">{{ele.track_name|safe}}</span>
              <p><br>
              </p>
              <a class="secondary-content"><i class="material-icons">{{ele.track_number}}</i></a>
            </li> </a>
            {% endfor %}
          </ul>

      </div>

      <div class="col s9">
           {{track.track_lyrics|safe|linebreaks}}
      </div>

    </div>
          
</div>

{% endblock %}